### PR TITLE
Add hdf5, idg, lofarbeam and wsclean

### PR DESCRIPTION
**Pull request by bramveenboer**
Add installation of several imaging related packages. I have tested this only on Astron/DAS-5 with the following software: centos/7, gcc/7.3.0, cmake/3.13.3, boost/1.66 and cuda/9.2.88. Furthermore, casarest fails to build (incompatible with GCC/7.3.0?) and I, therefore, have not attempted to build lofar either.

### CODE REVIEW

**Comment by bramveenboer** [comment]
I find it useful to have IDG and WSClean added to the scripts. However, as I pointed out, I am unable to build/test casarest and lofar. We might want to run this version of lofar-deploy through Jenkins to see whether it works or not.

**Comment by ygrange** [comment]
Why did the build of LOFAR disappear from the current ubuntu 16.04 dockerfile in this PR...?

**Comment by tammojan** [comment]
The offline data reduction packages were split off from LOFAR to DP3 and LofarBeam

**Comment by ygrange** [comment]
> The offline data reduction packages were split off from LOFAR to DP3 and LofarBeam
Ah sorry for deleting my comment while you were answering. Ik figured it was Brams previous comment.
So in essence I can provide this as the "offline packages" bit.

**Comment by bramveenboer** [comment]
The lofar-deploy code and the installed packages have been updated to work in Docker for Ubuntu 18.04 and CentOS 7.0.

**Comment by ygrange** [comment]
Good news!!

**Pull request merged**
